{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: featurehub
  namespace: {{ .Release.Namespace }}
  labels:
  {{- with .Values.global.ingress.annotations }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /features
            pathType: Prefix
            backend:
              service:
                name: "featurehub-edge"
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "featurehub-management-repository"
                port:
                  name: http
  {{- end }}