{{- if .Values.dacha.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-dacha-env
  labels:
    {{- include "featurehub.dacha.labels" . | nindent 4 }}
data:
{{- with .Values.dacha.environmentVars }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if .Values.global.knative }}
  # use the public port
  management-repository.url: http://featurehub-management-server:8085
{{- else }}
  # use the monitor port
  management-repository.url: http://featurehub-management-server:8701
{{- end }}
{{- if not .Values.global.knative }}
  monitor.port: "8701"
{{- end }}
  server.port: "8600"
{{- end }}
