{{- if .Values.dacha.enabled }}
{{- if not .Values.dacha.envAsApplicationProperties }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-dacha-env
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "featurehub.dacha.labels" . | nindent 4 }}
data:
{{- with .Values.dacha.environmentVars }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.global.environmentVars }}
  {{- toYaml . | nindent 2 }}
{{- end }}
  {{- include "google-pubsub-environment-env" . | nindent 2 }}
  monitor.port: "8701"
  server.port: "8600"
  dacha1.enabled: "false"
  dacha2.enabled: "true"
{{- end }}
{{- end }}
