{{- if .Values.dacha.enabled }}
{{- if .Values.dacha.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "featurehub.dacha.name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    {{- include "featurehub.dacha.labels" . | nindent 4 }}
    {{- with .Values.dacha.prometheus.labels }}
      {{- toYaml .  | nindent 4}}
    {{- end }}
spec:
  endpoints:
    - honorLabels: true
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      {{- include "featurehub.dacha.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
{{- end }}
