{{- if .Values.dacha.enabled }}
{{- if .Values.dacha.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "featurehub.dacha.serviceAccountName" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  {{- with .Values.dacha.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.dacha.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
