{{- if .Values.global.environmentVars }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-global-common-env
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "featurehub.managementRepository.labels" . | nindent 4 }}
data:
{{- with .Values.global.environmentVars }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
