{{- if .Values.edge.enabled }}
{{- if not .Values.edge.envAsApplicationProperties }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-edge-env
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "featurehub.edge.labels" . | nindent 4 }}
data:
{{- with .Values.edge.environmentVars }}
  {{- toYaml . | nindent 2 }}
{{- end }}
  {{- include "google-pubsub-environment-env" . | nindent 2 }}
  monitor.port: "8701"
  server.port: "8553"
  dacha1.enabled: "false"
  dacha2.enabled: "true"
  {{- if ne .Values.global.urlPath "" }}
  featurehub.url-path: {{ .Values.global.urlPath | quote }}
  {{- end }}
{{- end }}
{{- end }}
