{{- if .Values.edge.enabled }}
{{- if .Values.edge.envAsApplicationProperties }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-edge-app-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "featurehub.edge.labels" . | nindent 4 }}
data:
  application.properties: |-
    dacha1.enabled=false
    dacha2.enabled=true
    monitor.port=8701
    server.port=8553
{{- range $key, $value := .Values.edge.environmentVars }}
  {{- $key | nindent 4 }}={{ $value }}
{{- end -}}
  {{- include "google-pubsub-environment" . | nindent 4 }}
{{- end -}}
{{- end -}}
