{{- if .Values.edge.enabled }}
{{- if .Values.edge.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "featurehub.edge.serviceAccountName" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  {{- with .Values.edge.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.edge.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
