apiVersion: v1
kind: Service
metadata:
  name: {{ include "pubsub-emulator.fullname" . }}
  labels:
    {{- include "pubsub-emulator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default .Values.global.port }}
      targetPort: {{ .Values.global.port }}
      protocol: TCP
      name: pubsub
  selector:
    {{- include "pubsub-emulator.selectorLabels" . | nindent 4 }}
