{{- if .Values.managementRepository.enabled }}
{{- if and .Values.managementRepository.envAsApplicationProperties .Values.managementRepository.environmentVars }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-management-repository-app-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "featurehub.managementRepository.labels" . | nindent 4 }}
data:
  application.properties: |-
{{- range $key, $value := .Values.managementRepository.environmentVars }}
  {{- $key | nindent 4 }}={{ $value }}
{{- end -}}
{{- end -}}
{{- end -}}
