{{- if .Values.managementRepository.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-management-repository-env
  labels:
    {{- include "featurehub.managementRepository.labels" . | nindent 4 }}
data:
{{- with .Values.managementRepository.environmentVars }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if not .Values.global.knative }}
  monitor.port: "8701"
{{- end }}
  server.port: "8085"
  run.nginx: "true"
  {{- if .Values.global.intranet }}
  web.asset.location: "/var/www/html/intranet"
  {{- end }}
  {{- if ne .Values.global.urlPath "" }}
  featurehub.url-path: {{ .Values.global.urlPath | quote }}
  {{- end }}
{{- end }}
