{{- if .Values.managementRepository.enabled }}
{{- if .Values.managementRepository.envAsApplicationProperties }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-management-repository-app-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "featurehub.managementRepository.labels" . | nindent 4 }}
data:
  application.properties: |-
    monitor.port=8701
    server.port=8085
    run.nginx=true
    dacha1.enabled=false
    dacha2.enabled=true
{{- range $key, $value := .Values.managementRepository.environmentVars }}
  {{- $key | nindent 4 }}={{ $value }}
{{- end -}}
  {{- include "google-pubsub-environment" . | nindent 4 }}
  {{- include "google-pubsub-mr" . | nindent 4 }}
{{- end -}}
{{- end -}}
