{{- if .Values.managementRepository.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "featurehub.managementRepository.name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  labels:
    {{- include "featurehub.managementRepository.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: http
      protocol: TCP
      name: http
    - port: 8701
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "featurehub.managementRepository.selectorLabels" . | nindent 4 }}
{{- end }}
