{{- if .Values.managementRepository.enabled }}
{{- if .Values.managementRepository.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "featurehub.managementRepository.serviceAccountName" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  {{- with .Values.managementRepository.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.managementRepository.serviceAccount.annotations }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
