name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'helm/featurehub/**'
jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.6.1
      - name: Dependency install
        run: helm dependency update
        working-directory: helm/featurehub
      - name: Run basic lint
        run: helm lint
        working-directory: helm/featurehub
      - name: Run lint
        run: |
          helm repo add bitnami https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/
          ct lint --config ../../.github/ct.yaml --chart-dirs . --charts . --target-branch ${{ github.event.repository.default_branch }}
        working-directory: helm/featurehub

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2
      - name: Dependency install
        run: helm dependency update
        working-directory: helm/featurehub
      - name: Run helm-docs
        run: bash .github/helm-docs.sh

